// actions
export const SET_CONTAINERS = 'SET_CONTAINERS';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
// mutations

// getters
export const GET_CONTAINERS = 'GET_CONTAINERS';

export const GET_CONTAINERS_BY_TYPE = 'GET_CONTAINERS_BY_TYPE';

export const GET_LAST_UPDATED_DATE_BY_TYPE = 'GET_LAST_UPDATED_DATE_BY_TYPE';
